### ISSUE TITLE
Document Mac installation

### ISSUE THREAD

**Issue by ollycostello** [anthwlock/untrunc#142]
It doesn't seem too well documented how the installation should go for Mac users.

Is it just:
* clone repo
* `cd` inside it
* run `make`

I'm getting the `make: *** [.build_shared/src/codec.o] Error 1` error which is reported in https://github.com/anthwlock/untrunc/issues/140 which is blocking me getting any further but because the readme only describes installation for windows or linux I'm not 100% I've done things right.

**Comment by KenjiTakahashi** [comment]
It is the right way for macOS as well. It used to work, before `FFmpeg` 6 got released.
I suppose you could roll back to older FFmpeg version (for home-brew: remove `ffmpeg` and install sth like `ffmpeg@5` or `ffmpeg@4`), but not tested.

**Comment by thpryrchn** [comment]
This works: https://github.com/anthwlock/untrunc/issues/131#issuecomment-1415408517

as stated in there:
```bash
git clone https://github.com/anthwlock/untrunc.git
cd untrunc
brew install wget
make FF_VER=3.3.9
sudo cp untrunc /usr/local/bin
```

**Comment by medikoo** [comment]
Above method unfortunately fails on Sonoma (14.4.1)

```
libavcodec/aarch64/h264dsp_init_aarch64.c:84:38: error: incompatible function pointer types assigning to 'h264_weight_func' (aka 'void (*)(unsigned char *, long, int, int, int, int)') from 'void (uint8_t *, int, int, int, int, int)' (aka 'void (unsigned char *, int, int, int, int, int)') [-Wincompatible-function-pointer-types]
        c->weight_h264_pixels_tab[0] = ff_weight_h264_pixels_16_neon;
                                     ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libavcodec/aarch64/h264dsp_init_aarch64.c:85:38: error: incompatible function pointer types assigning to 'h264_weight_func' (aka 'void (*)(unsigned char *, long, int, int, int, int)') from 'void (uint8_t *, int, int, int, int, int)' (aka 'void (unsigned char *, int, int, int, int, int)') [-Wincompatible-function-pointer-types]
        c->weight_h264_pixels_tab[1] = ff_weight_h264_pixels_8_neon;
                                     ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libavcodec/aarch64/h264dsp_init_aarch64.c:86:38: error: incompatible function pointer types assigning to 'h264_weight_func' (aka 'void (*)(unsigned char *, long, int, int, int, int)') from 'void (uint8_t *, int, int, int, int, int)' (aka 'void (unsigned char *, int, int, int, int, int)') [-Wincompatible-function-pointer-types]
        c->weight_h264_pixels_tab[2] = ff_weight_h264_pixels_4_neon;
                                     ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libavcodec/aarch64/h264dsp_init_aarch64.c:88:40: error: incompatible function pointer types assigning to 'h264_biweight_func' (aka 'void (*)(unsigned char *, unsigned char *, long, int, int, int, int, int)') from 'void (uint8_t *, uint8_t *, int, int, int, int, int, int)' (aka 'void (unsigned char *, unsigned char *, int, int, int, int, int, int)') [-Wincompatible-function-pointer-types]
        c->biweight_h264_pixels_tab[0] = ff_biweight_h264_pixels_16_neon;
                                       ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libavcodec/aarch64/h264dsp_init_aarch64.c:89:40: error: incompatible function pointer types assigning to 'h264_biweight_func' (aka 'void (*)(unsigned char *, unsigned char *, long, int, int, int, int, int)') from 'void (uint8_t *, uint8_t *, int, int, int, int, int, int)' (aka 'void (unsigned char *, unsigned char *, int, int, int, int, int, int)') [-Wincompatible-function-pointer-types]
        c->biweight_h264_pixels_tab[1] = ff_biweight_h264_pixels_8_neon;
                                       ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libavcodec/aarch64/h264dsp_init_aarch64.c:90:40: error: incompatible function pointer types assigning to 'h264_biweight_func' (aka 'void (*)(unsigned char *, unsigned char *, long, int, int, int, int, int)') from 'void (uint8_t *, uint8_t *, int, int, int, int, int, int)' (aka 'void (unsigned char *, unsigned char *, int, int, int, int, int, int)') [-Wincompatible-function-pointer-types]
        c->biweight_h264_pixels_tab[2] = ff_biweight_h264_pixels_4_neon;
                                       ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
6 errors generated.
make[1]: *** [libavcodec/aarch64/h264dsp_init_aarch64.o] Error 1
make: *** [ffmpeg-3.3.9/libavcodec/libavcodec.a] Error 2
```

**Comment by alvins82** [comment]
Try this -

make FF_VER=3.3.9 EXTRA_FF_OPTS="--extra-cflags=\"-Wno-error=incompatible-function-pointer-types -Wno-int-conversion\""

**Comment by illogikk** [comment]
@medikoo I tested this with a newer version of FFMPEG and got it to compile in Sequoia 15.3  _which_ might help for Sonoma. 

Try `make FF_VER=6.0.1`

**Comment by brandon-fryslie** [comment]
> make FF_VER=6.0.1

Built successfully for me on Tahoe.  Seems to run alright, no issues so far.

**Comment by hchauvat** [comment]
I couldn't make any FF version work, (tried 3.3.9, 6.0.1 and even 8.0.1 which is the one that seems to be currently on my mac). Only the [Docker](https://github.com/anthwlock/untrunc/wiki/Installing-on-macOS) approach by @sk9c00 worked. And I must say thank you, because you saved my butt!

**Comment by anthwlock** [comment]
@hchauvat 

Did you try the [instructions from the README](https://github.com/anthwlock/untrunc?tab=readme-ov-file#macos-with-homebrew) using brew? If they failed, what was the exact error? I am unable to test, since I don't have access to a MAC.

**Comment by hchauvat** [comment]
> [@hchauvat](https://github.com/hchauvat)
> 
> Did you try the [instructions from the README](https://github.com/anthwlock/untrunc?tab=readme-ov-file#macos-with-homebrew) using brew? If they failed, what was the exact error? I am unable to test, since I don't have access to a MAC.

Yes, I did the following:

```sh
➜  git clone https://github.com/anthwlock/untrunc.git untrunc
➜  cd untrunc
➜  untrunc git:(master) brew install ffmpeg yasm
```
> ffmpeg-full includes additional tools and libraries that are not included in the regular ffmpeg formula.
```sh
➜  untrunc git:(master) CPPFLAGS="-I/opt/homebrew/include" LDFLAGS="-L/opt/homebrew/lib" make
````
> untrunc: v388-d286625
> ffmpeg: shared
> 
> c++ -I/opt/homebrew/include -MMD -MP -DUNTR_VERSION=\"v388-d286625\" -isystem/usr/include/ffmpeg -std=c++17 -D_FILE_OFFSET_BITS=64 -g -o .build_shared/src/atom.o -c src/atom.cpp
> In file included from src/atom.cpp:1:
> src/atom.h:6:10: fatal error: 'vector' file not found
>     6 | #include <vector>
>       |          ^~~~~~~~
> 1 error generated.
> make: *** [.build_shared/src/atom.o] Error 1
```sh
➜  untrunc git:(master) brew install wget
➜  untrunc git:(master) make FF_VER=6.0.1
```

> (info) downloading ffmpeg-6.0.1 ...
> curl -o /tmp/ffmpeg-6.0.1.tar.xz https://www.ffmpeg.org/releases/ffmpeg-6.0.1.tar.xz
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  9.7M  100  9.7M    0     0  11.9M      0 --:--:-- --:--:-- --:--:-- 11.9M
> tar xf /tmp/ffmpeg-6.0.1.tar.xz
> mv ffmpeg-6.0.1/VERSION ffmpeg-6.0.1/VERSION.bak
> (info) please wait ...
> cd ffmpeg-6.0.1; ./configure --disable-doc --disable-programs \
> 	--disable-everything --enable-decoders --disable-vdpau --enable-demuxers --enable-protocol=file \
> 	--disable-avdevice --disable-swresample --disable-swscale --disable-avfilter --disable-postproc \
> 	--disable-xlib --disable-vaapi --disable-zlib --disable-bzlib --disable-lzma \
> 	--disable-audiotoolbox --disable-videotoolbox
> gcc is unable to create an executable file.
> If gcc is a cross-compiler, use the --enable-cross-compile option.
> Only do this if you know what cross compiling means.
> C compiler test failed.
> 
> If you think configure made a mistake, make sure you are using the latest
> version from Git.  If the latest version fails, report the problem to the
> ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
> Include the log file "ffbuild/config.log" produced by configure as this will help
> solve the problem.
> make: *** [ffmpeg-6.0.1/config.asm] Error 1
```sh
➜  untrunc git:(master) make
```
> untrunc: v388-d286625
> ffmpeg: shared
> 
> c++ -I/opt/homebrew/opt/llvm/include -MMD -MP -DUNTR_VERSION=\"v388-d286625\" -isystem/usr/include/ffmpeg -std=c++17 -D_FILE_OFFSET_BITS=64 -g -o .build_shared/src/atom.o -c src/atom.cpp
> In file included from src/atom.cpp:1:
> src/atom.h:6:10: fatal error: 'vector' file not found
>     6 | #include <vector>
>       |          ^~~~~~~~
> 1 error generated.
> make: *** [.build_shared/src/atom.o] Error 1
```sh
➜  untrunc git:(master) make FF_VER=3.3.9
```

> (info) downloading ffmpeg-3.3.9 ...
> curl -o /tmp/ffmpeg-3.3.9.tar.xz https://www.ffmpeg.org/releases/ffmpeg-3.3.9.tar.xz
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 8101k  100 8101k    0     0  10.2M      0 --:--:-- --:--:-- --:--:-- 10.2M
> tar xf /tmp/ffmpeg-3.3.9.tar.xz
> mv ffmpeg-3.3.9/VERSION ffmpeg-3.3.9/VERSION.bak
> (info) please wait ...
> cd ffmpeg-3.3.9; ./configure --disable-doc --disable-programs \
> 	--disable-everything --enable-decoders --disable-vdpau --enable-demuxers --enable-protocol=file \
> 	--disable-avdevice --disable-swresample --disable-swscale --disable-avfilter --disable-postproc \
> 	--disable-xlib --disable-vaapi --disable-zlib --disable-bzlib --disable-lzma \
> 	--disable-audiotoolbox --disable-videotoolbox --disable-vda
> gcc is unable to create an executable file.
> If gcc is a cross-compiler, use the --enable-cross-compile option.
> Only do this if you know what cross compiling means.
> C compiler test failed.
> 
> If you think configure made a mistake, make sure you are using the latest
> version from Git.  If the latest version fails, report the problem to the
> ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
> Include the log file "config.log" produced by configure as this will help
> solve the problem.
> make: *** [ffmpeg-3.3.9/config.asm] Error 1
```sh
➜  untrunc git:(master) brew install ffmpeg
```
> Warning: ffmpeg 8.0.1_4 is already installed and up-to-date.
> To reinstall 8.0.1_4, run:
>   brew reinstall ffmpeg
```sh
➜  untrunc git:(master) make FF_VER=8.0.1_4
```

> (info) downloading ffmpeg-8.0.1_4 ...
> curl -o /tmp/ffmpeg-8.0.1_4.tar.xz https://www.ffmpeg.org/releases/ffmpeg-8.0.1_4.tar.xz
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   189  100   189    0     0   1310      0 --:--:-- --:--:-- --:--:--  1312
> tar xf /tmp/ffmpeg-8.0.1_4.tar.xz
> tar: Error opening archive: Unrecognized archive format
> make: *** [ffmpeg-8.0.1_4/configure] Error 1
```sh
➜  untrunc git:(master) make FF_VER=8.0.1
```

> (info) downloading ffmpeg-8.0.1 ...
> curl -o /tmp/ffmpeg-8.0.1.tar.xz https://www.ffmpeg.org/releases/ffmpeg-8.0.1.tar.xz
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 10.8M  100 10.8M    0     0  6899k      0  0:00:01  0:00:01 --:--:-- 6895k
> tar xf /tmp/ffmpeg-8.0.1.tar.xz
> mv ffmpeg-8.0.1/VERSION ffmpeg-8.0.1/VERSION.bak
> (info) please wait ...
> cd ffmpeg-8.0.1; ./configure --disable-doc --disable-programs \
> 	--disable-everything --enable-decoders --disable-vdpau --enable-demuxers --enable-protocol=file \
> 	--disable-avdevice --disable-swresample --disable-swscale --disable-avfilter --disable-postproc \
> 	--disable-xlib --disable-vaapi --disable-zlib --disable-bzlib --disable-lzma \
> 	--disable-audiotoolbox --disable-videotoolbox
> Unknown option "--disable-postproc".
> See ./configure --help for available options.
> make: *** [ffmpeg-8.0.1/config.asm] Error 1

TBH, I'm not familiar with make or ffmpeg, so I probably did a mistake somewhere. If so, i'm really sorry

**Comment by anthwlock** [comment]
@hchauvat Thanks, it looks to me like there is an issue with your c++ compiler setup. Does the following help?

```
sudo xcode-select --reset
sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install
```

**Comment by hchauvat** [comment]
@anthwlock It's seems reinstalling xcode-select did the trick, thanks a lot
